# coding: UTF-8

from code.CodeValue import CodeValue

class PREFECTURE():
    u"""都道府県"""
    
    hokkaidou =CodeValue(1, "北海道")
    aomori =CodeValue(2, "青森")
    iwate =CodeValue(3, "岩手")
    miyagi =CodeValue(4, "宮城")
    akita =CodeValue(5, "秋田")
    yamagata =CodeValue(6, "山形")
    hukushima =CodeValue(7, "福島")
    ibaraki =CodeValue(8, "茨城")
    tochigi =CodeValue(9, "栃木")
    gunma =CodeValue(10, "群馬")
    saitama =CodeValue(11, "埼玉")
    chiba =CodeValue(12, "千葉")
    tokyo =CodeValue(13, "東京")
    kanagawa =CodeValue(14, "神奈川")
    niigata =CodeValue(15, "新潟")
    toyama =CodeValue(16, "富山")
    ishikawa =CodeValue(17, "石川")
    fukui =CodeValue(18, "福井")
    yamanashi =CodeValue(19, "山梨")
    nagano =CodeValue(20, "長野")
    gifu =CodeValue(21, "岐阜")
    shizuoka =CodeValue(22, "静岡")
    aichi =CodeValue(23, "愛知")
    mie =CodeValue(24, "三重")
    shiga =CodeValue(25, "滋賀")
    kyoto =CodeValue(26, "京都")
    osaka =CodeValue(27, "大阪")
    hyogo =CodeValue(28, "兵庫")
    nara =CodeValue(29, "奈良")
    wakayama =CodeValue(30, "和歌山")
    tottori =CodeValue(31, "鳥取")
    shimane =CodeValue(32, "島根")
    okayama =CodeValue(33, "岡山")
    hiroshima =CodeValue(34, "広島")
    yamaguchi =CodeValue(35, "山口")
    tokushima =CodeValue(36, "徳島")
    kagawa =CodeValue(37, "香川")
    ehime =CodeValue(38, "愛媛")
    kouchi =CodeValue(39, "高知")
    hukuoka =CodeValue(40, "福岡")
    saga =CodeValue(41, "佐賀")
    nagasaki =CodeValue(42, "長崎")
    kumamoto =CodeValue(43, "熊本")
    oita =CodeValue(44, "大分")
    miyazaki =CodeValue(45, "宮崎")
    kagoshima =CodeValue(46, "鹿児島")
    okinawa =CodeValue(47, "沖縄")
    
    
